In [55]:
import pandas as pd
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv")
df.head(2)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult

In [56]:
df.shape

(11552, 85)

In [57]:
df[df.duplicated()].shape[0]

154

In [58]:
df1=df['Respondent']
df1[df1.duplicated()].shape[0]

154

In [59]:
df=df.drop_duplicates()
df.shape

(11398, 85)

In [60]:
df[df.duplicated()].shape[0]

0

In [61]:
df1=df['EdLevel']
print(df1.isnull().sum())

112

In [62]:
df1=df['Country']
print(df1.isnull().sum())

0

In [34]:
print(df.isnull().sum())

Respondent        0
MainBranch        0
Hobbyist          0
OpenSourcer       0
OpenSource       81
               ...
Sexuality       542
Ethnicity       675
Dependents      140
SurveyLength     19
SurveyEase       14
Length: 85, dtype: int64

In [63]:
df['WorkLoc'].isnull().sum()

32

In [64]:
df['WorkLoc'].describe()

count      11366
unique         3
top       Office
freq        6806
Name: WorkLoc, dtype: object

In [65]:
df['Employment'].describe()

count                  11398
unique                     2
top       Employed full-time
freq                   10968
Name: Employment, dtype: object

In [70]:
df1=df.groupby('UndergradMajor').nunique()
df1['Respondent'].min()
df1

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
UndergradMajor,,,,,,,,,,,,,,,,,,,,,
"A business discipline (ex. accounting, finance, marketing)",244,2,2,4,3,2,50,3,6,97,...,6,15,36,4,1,4,16,2,3,3
"A health science (ex. nursing, pharmacy, radiology)",24,2,2,4,3,1,13,2,5,18,...,4,11,14,3,2,3,7,2,3,3
"A humanities discipline (ex. literature, history, philosophy)",207,2,2,4,3,2,31,3,6,98,...,6,14,37,6,2,5,15,2,3,2
"A natural science (ex. biology, chemistry, physics)",403,2,2,4,3,2,59,3,6,122,...,6,15,40,4,2,5,16,2,3,3
"A social science (ex. anthropology, psychology, political science)",210,2,2,4,3,2,35,3,6,95,...,6,15,31,4,2,4,20,2,3,3
"Another engineering discipline (ex. civil, electrical, mechanical)",759,2,2,4,3,2,78,3,6,178,...,6,15,42,5,2,6,24,2,3,3
"Computer science, computer engineering, or software engineering",6953,2,2,4,3,2,126,3,6,369,...,6,15,57,7,2,7,74,2,3,3
"Fine arts or performing arts (ex. graphic design, music, studio art)",161,2,2,4,3,2,26,3,5,83,...,4,15,30,5,2,4,16,2,3,2
I never declared a major,124,2,2,4,3,2,31,3,5,67,...,6,15,35,2,1,3,10,2,3,3
"Information systems, information technology, or system administration",794,2,2,4,3,2,86,3,6,175,...,6,15,42,4,2,4,32,2,3,3
Mathematics or statistics,372,2,2,4,3,2,58,3,6,123,...,6,15,42,5,2,4,23,2,3,3
Web development or web design,410,2,2,4,3,2,65,3,5,143,...,6,15,31,3,2,5,26,2,3,3

In [71]:
df['WorkLoc'].fillna('Office', inplace=True)
df['WorkLoc'].isnull().sum()

0

In [72]:
df['CompFreq'].unique().tolist()

['Yearly', 'Monthly', 'Weekly', nan]

In [74]:
df1=df.groupby('CompFreq').nunique()
df1

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
CompFreq,,,,,,,,,,,,,,,,,,,,,
Monthly,4788,2,2,4,3,2,132,3,9,12,...,6,15,51,7,2,6,70,2,3,3
Weekly,331,2,2,4,3,2,33,3,9,12,...,5,15,40,3,2,5,26,2,3,3
Yearly,6073,2,2,4,3,2,92,3,9,12,...,6,15,57,7,2,7,64,2,3,3

In [75]:
df['CompFreq'].isnull().sum()

206

In [76]:
df['CompTotal'].isnull().sum()

809

In [77]:
df['NormalizedAnnualCompensation'] = [mult*52 if crit == 'Weekly' 
                                                  else (mult*12 if crit == 'Monthly' 
                                                        else mult) for crit, mult in zip(df['CompFreq'], df['CompTotal'])]

In [78]:
df[['NormalizedAnnualCompensation','CompFreq','CompTotal']]

       NormalizedAnnualCompensation CompFreq  CompTotal
0                           61000.0   Yearly    61000.0
1                          138000.0   Yearly   138000.0
2                           90000.0   Yearly    90000.0
3                          348000.0  Monthly    29000.0
4                           90000.0   Yearly    90000.0
...                             ...      ...        ...
11547                      130000.0   Yearly   130000.0
11548                       74400.0   Yearly    74400.0
11549                      105000.0   Yearly   105000.0
11550                       80000.0   Yearly    80000.0
11551                           NaN      NaN        NaN

[11398 rows x 3 columns]

In [79]:
df['NormalizedAnnualCompensation'].median()

100000.0